### ISSUE TITLE
Dump near headers and run NearBridge tests on them

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#102]
We need to write a code that would dump Near light headers using: 
```bash
http post http://127.0.0.1:3030/ jsonrpc=2.0 method=next_light_client_block params:='["E8K1A51oMR5PkotxNGNkDnVQ9knD4WLn8oDcettqiZbn"]' id="dontcare"
```
Then we would like to run NearBridge against them like it is done here: https://github.com/near/rainbow-bridge/blob/810267b21d12c21dab75892e76c3a9904861b6cd/libs-sol/nearbridge/test/NearBridge.js#L91

**Comment by ailisp** [comment]
This is the dump near header command?

**Comment by nearmax** [comment]
This is done, thanks @ailisp
