### ISSUE TITLE
Upgrade nearlib to the most recent near-api-js

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#110]
Currently we are using nearlib, but we should be using the most recent `near-api-js`.
Upgrading might require refactoring some code.

**Comment by nearmax** [comment]
@fckt Could you please take a look at it?

**Comment by willemneal** [comment]
Just noticed that the `yarn-error.log` is checked it.  Is this intentional?

**Comment by willemneal** [comment]
I was able to add a `tsconfig.json` to that checks the js to find all the breaking APIs.

**Comment by chefsale** [comment]
I think the yarn.error should be deleted.

**Comment by willemneal** [comment]
Yeah I ended up removing it from #116.
