### ISSUE TITLE
transfer-eth-erc20-to-near hangs after execution

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#112]
`transfer-eth-erc20-to-near` command does hangs at the end of the execution, maybe because either nearlib or web3 is holding a socket.

**Comment by chefsale** [comment]
Hmmm, getting these errors:
```
1|eth-rela | Error: Querying call/eth2nearclient/last_block_number failed: wasm execution failed with error: FunctionCallError(HostError(GuestPanic { panic_msg: "EthBridge is not initialized" })).
1|eth-rela | {
1|eth-rela |   "error": "wasm execution failed with error: FunctionCallError(HostError(GuestPanic { panic_msg: \"EthBridge is not initialized\" }))",
1|eth-rela |   "logs": [],
1|eth-rela |   "block_height": 338,
1|eth-rela |   "block_hash": "4S23cQ1icHF7o1ZpFFDj4Us3yxQpNY9oqSYJCKZ32j95"
1|eth-rela | }
1|eth-rela |     at JsonRpcProvider.query (/home/sandi/workspace/near/bridge/environment/node_modules/nearlib/lib/providers/json-rpc-provider.js:35:19)
1|eth-rela |     at process._tickCallback (internal/process/next_tick.js:68:7)
```
and
```
(node:344075) UnhandledPromiseRejectionWarning: Error: Querying call/eth2nearclient/last_block_number failed: wasm execution failed with error: FunctionCallError(HostError(GuestPanic { panic_msg: "EthBridge is not initialized" })).
{
  "error": "wasm execution failed with error: FunctionCallError(HostError(GuestPanic { panic_msg: \"EthBridge is not initialized\" }))",
  "logs": [],
  "block_height": 407,
  "block_hash": "GeZTi8hUY66trhc1BKgy6tDXZQ1kDe9EFRBzKj4AEwAo"
}
    at JsonRpcProvider.query (/home/sandi/workspace/near/bridge/environment/node_modules/nearlib/lib/providers/json-rpc-provider.js:35:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:344075) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:344075) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
not sure if that is expected?

**Comment by bowenwang1996** [comment]
@chefsale did you initialize the contract?

**Comment by ailisp** [comment]
In test it's not really matter to do a proper clean up, so i just add a process.exit(0) after success checks done.

**Comment by chefsale** [comment]
I've ran all of these sequentially:
node index.js init-near-contracts
node index.js init-eth-ed25519
node index.js init-near2eth-client
node index.js init-eth-erc20
node index.js init-eth-locker

**Comment by ailisp** [comment]
Close as it doesn't stuck:
https://buildkite.com/nearprotocol/rainbow-bridge/builds/113#e75f4ac7-1cab-4a82-822c-70c7a7fc9bda

@chefsale Did your 
>  node index.js init-near-contracts

show no error messages?

**Comment by chefsale** [comment]
Let's leave it open until we really verify this is not an issue, I didn't get the hang but maybe it happens occasionally due to some socker race as max said.

**Comment by ailisp** [comment]
> Let's leave it open until we really verify this is not an issue, I didn't get the hang but maybe it happens occasionally due to some socker race as max said.

It doesn't worth to investigate, If you'd really like you can, we almost certainly just want to just shutdown these handles at test exit, so simple process.exit(0) does this for you.
```
process._getActiveRequests()
process._getActiveHandles()
```
