### ISSUE TITLE
Dump Near headers and run them against Near2EthClient

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#115]
Similarly to what we did with Eth headers and proofs we need to implement a command that would dump Near headers and then run them through the Near2EthClient. For an example of the Near2EthClient test that accepts Near headers see: https://github.com/near/rainbow-bridge/blob/810267b21d12c21dab75892e76c3a9904861b6cd/libs-sol/nearbridge/test/NearBridge.js#L91

**Comment by ailisp** [comment]
Is this one duplicate of #102 ?

**Comment by nearmax** [comment]
Yes, sorry.
