### ISSUE TITLE
Enable solidity tests on CI

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#128]
Currently one can run solidity tests by going to `nearbridge` or `nearprover` and running `yarn test`. Unfortunately, this is not run on the CI. Also @fckt has recently added https://github.com/near/rainbow-bridge/pull/127 which should also run on CI.

Also, note that the following assertion will break: https://github.com/near/rainbow-bridge/blob/44fd2b5daa205bfd5c552df1e7061eb6d7147333/libs-sol/nearbridge/test/NearBridge.js#L83 This is because with the current constant https://github.com/near/rainbow-bridge/blob/44fd2b5daa205bfd5c552df1e7061eb6d7147333/libs-sol/nearbridge/contracts/NearBridge.sol#L36 the block becomes almost immediately valid. In production this constant needs to be high (several hours) but in testing it needs to be low (like 10 seconds). We need to replace `LOCK_ETH_AMOUNT` and `LOCK_DURATION` constant with fields that are initialized from the constructor and we should pass small amounts there during the test, and large amounts for the production. For this specific issue we can just comment out that specific assertion, @nearmax will fix it later.

**Comment by ailisp** [comment]
> Currently one can run solidity tests by going to nearbridge or nearprover and running yarn test. Unfortunately, this is not run on the CI. Also @fckt has recently added #127 which should also run on CI.

I think this is not true, they're running on ci: https://buildkite.com/nearprotocol/rainbow-bridge/builds/168#387eb4fb-d5b6-44e3-a525-7939a9c4caf3 , under "near bridge test" and "near prover test"

>  the block becomes almost immediately valid. In production this constant needs to be high (several hours) but in testing it needs to be low (like 10 seconds). We need to replace LOCK_ETH_AMOUNT and LOCK_DURATION constant with fields that are initialized from the constructor and we should pass small amounts there during the test, and large amounts for the production. For this specific issue we can just comment out that specific assertion, @nearmax will fix it later.

Makes sense to me, will do

**Comment by ailisp** [comment]
Addressed in #131

**Comment by nearmax** [comment]
Closing then.
