### ISSUE TITLE
Problem with rainbow up workflow and e2e test

### ISSUE THREAD

**Issue by ailisp** [near/rainbow-bridge#132]
Currently how environment index.js works is problematic, it always clone master branch and launch rainbow bridge services based on that. However, the control commands (enviroment/index.js) are using current branch one. This result in hard to reason about. (which copy of near/solidity contracts are used? which ethashproof go binary is used? which near-relay and eth-relay is used?) I think environment/index.js can reuse ~/.nearup and ~/.near, but for bridge source, it should always use current dir's bridge version.

**Comment by nearmax** [comment]
Fixed.
