### ISSUE TITLE
Handle killed pm2 daemon

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#143]
Our `clean` command kills pm2 daemon, which means that sometimes when we do `start eth-relay` or other service they won't start, because we need to call `pm2 ping` first. We should fix it and call `ping` for every command that starts new daemon under pm2 daemon.

**Comment by ailisp** [comment]
I cannot reproduce locally. And notice that there isn't a pm2.ping (programmatic api): https://pm2.keymetrics.io/docs/usage/pm2-api/#programmatic-api
but instead, connect will spawn a new daemon if the old is killed. In our code spawnProcess (in eth-relay) happens after connect, and test result is connect start a daemon and eth-relay is started

**Comment by ailisp** [comment]
During test this, find a weird behavior of daemon option:
```
$ node index.js start eth-relay
eth-relay service is not running...
Starting eth-relay with command:
index.js ['start', 'eth-relay', '--daemon', 'false']
eth-relay started...
Disconnection from daemon

$ node index.js start eth-relay --daemon true
eth-relay service is not running...
Starting eth-relay with command:
index.js ['start', 'eth-relay', '--daemon', 'false']
eth-relay started...
Disconnection from daemon
```
And looks it's intentional:
https://github.com/near/rainbow-bridge/blob/master/environment/commands/start/eth-relay.js#L24
https://github.com/near/rainbow-bridge/blob/master/environment/lib/config.js#L96

Why? @chefsale

**Comment by nearmax** [comment]
@ailisp That's how it should behave. --daemon is `true` by default. When we call `node index.js start eth-relay --daemon true` the cli uses pm2 to start the following command wrapped as a daemon `node index.js start eth-relay --daemon false`: https://github.com/near/rainbow-bridge/blob/master/environment/commands/start/eth-relay.js#L10

It is a recursion.

**Comment by ailisp** [comment]
> @ailisp That's how it should behave. --daemon is true by default. When we call node index.js start eth-relay --daemon true the cli uses pm2 to start the following command wrapped as a daemon node index.js start eth-relay --daemon false: https://github.com/near/rainbow-bridge/blob/master/environment/commands/start/eth-relay.js#L10

I see, the code behavior is as expected, may be should not output
```
index.js ['start', 'eth-relay', '--daemon', 'false']
```
in this case, which looks confusing

**Comment by nearmax** [comment]
I agree

**Comment by nearmax** [comment]
Cannot reproduce it.
