### ISSUE TITLE
Rewrite eth-object library

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#147]
As discovered in https://github.com/near/rainbow-bridge/issues/140 eth-object library is buggy. It is also maintained by one person. We need to get rid of it, either find a more popular alternative or rewrite it ourselves following Ethereum specs. Please keep in mind that RLP spec has not well-known corner cases. If we choose to rewrite then we should cover it with extensive tests that cover corner cases.

**Comment by ailisp** [comment]
got an interesting finding. eth-object handles correctly on eth jsonrpc response, but not web3. The difference is rpc response difficulty as number in hex in string (e.g. '0x0'), but web3 give you number (e.g. '0'). see: https://eth.wiki/json-rpc/API#example-27

https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html#id43

And eth-object uses `toBuffer(rpcResult.difficulty)`
which did correct thing when difficulty is given as string hex number, but not when it is not:
```
> toBuffer('0')
<Buffer 30>
> toBuffer('0x')
<Buffer >
> toBuffer('0x0')
<Buffer >
> toBuffer(0)
<Buffer 00>
```

This means if we indeed use eth-jsonrpc directly (not web3), eth-object is good (as eth-object's api suggest, it's `fromRpc`), if we stick to web3, we can
1) do a preprocessing, convert all number in response to hex string (how eth-jsonrpc respond), before feeding to eth-object.fromRpc
2) Or, adding web3.utils.toHex for any number arguments in our eth-object fork, so methods like Header.fromRpc will also do the work of Header.fromWeb3, WDYT is better?

**Comment by ailisp** [comment]
Also find an alternative to eth-object which is official and suppose to be robust. https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/block/src/header-from-rpc.ts

**Comment by ailisp** [comment]
in #163
