### ISSUE TITLE
Robust e2e test on CI

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#149]
It is important to have a robust end-to-end test running on CI, which we can do by fixing https://github.com/near/rainbow-bridge/pull/134 . Unfortunately, we might need to fix https://github.com/near/rainbow-bridge/issues/142 first.

**Comment by ailisp** [comment]
Most of issues has been addressed in #134, there's another nonce issue in createAccount and deployContract, is addressed in #166
