### ISSUE TITLE
Hash computation of some NEAR headers is broken

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#165]
Checkout https://github.com/near/rainbow-bridge/pull/164
Then go to `libs-sol/nearbridge` and run `yarn test` observe that the test is failing because hash computation of the header is not correct. This block was taken from the testnet and you can re-request it with the following command:
```
http post https://rpc.testnet.near.org jsonrpc=2.0 id=dontcare \
    method=block \
    params:='{"block_id": 9274566}'
```

**Comment by bowenwang1996** [comment]
Sorry about that. The last commit on stable accidentally broke light client and the fix wasn't yet released to stable. We will release a new testnet version on Monday and that should resolve the issue.
