### ISSUE TITLE
When transfer-eth-erc20-to-near fails it wipes the config

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#176]
As reported by the users when transfer-eth-erc20-to-near fails it wipes the config. This should not be happening.

**Comment by ailisp** [comment]
Cannot reproduce by simulate a fail and didn't find any `RainbowConfig.saveConfig()` in `transfer-eth-erc20-to-near`, only getParams so this should not happening. Can you provide more details of the fail? Like do you remember which step it failed, what stack trace was printed and if possible, can you reproduce this one more time?

**Comment by nearmax** [comment]
Setting P2 priority since only one person was able to observe it. Here is the command and stdout from the user:

> node index.js transfer-eth-erc20-to-near --amount 100 --eth-sender-sk "<some_key>" --near-receiver-account "bridge-test.testnet" --near-master-account "bridge-test.testnet" --near-master-sk "ed25519:<some_key>"
> 
> if I put some logs in the the command:
> 
> console.log('Approving token transfer.');
>             console.log(ethSenderAccount);
>             console.log("eth-lcoker", RainbowConfig.getParam('eth-locker-address'));
> 
> logs: 
> Approving token transfer.
> 0xe3628e6AB18A6B0F60Ed8540690d18b6d9C88a46
> eth-lcoker 
> Failure.

**Comment by mfornet** [comment]
Can't reproduce this locally. Will close for now, and reopen if we hit this issue again.

Also for transfers users should use UI, or follow documentation (step-by-step-guide) rather than using `transfer-eth-erc20-to-near` command written for testing purposes.
