### ISSUE TITLE
eth-relay does not catch up with Eth fast enough

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#184]
Currently when eth-relay falls behind due to crash like https://github.com/near/rainbow-bridge/issues/183 we need to manually restart it. Manual restart requires Eth2NearClient requires the client to catch up with the network. Unfortunately it catches up approximately 3 blocks/minute (the gap between the most recent block of Eth2NearClient and Ethereum blockchain closes approx 3 blocks/minute) which means a 12-hour downtime of the eth-relay will require 17 hours to catchup. We need to investigate how to speed it up, since we are only limited by the speed of talking to Eth blockchain and submitting transactions to NEAR blockchain.

**Comment by ailisp** [comment]
Fix #183 in #205  immediately reconnect web3 to getBlock, there'll be no downtime of eth-relay. so i think it's no longer a serious issue, making it P2?

**Comment by nearmax** [comment]
I think it is still important, because if eth-relay goes down for whatever reason we should be able to catch up fast.

**Comment by nearmax** [comment]
This is getting even more important now, because our NEAR nodes sometimes stop serving RPC queries which causes bridge to fall back behind for several days, see: https://github.com/near/rainbow-bridge/issues/223
