### ISSUE TITLE
[Discussion] Near headers on the boundary of the epoch are not verifiable and should be skipped

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#189]
According to https://nomicon.io/ChainSpec/LightClient.html `approvals_after_next` sign the next block, however there is no information whether next block is `epoch_id` or `next_epoch_id`. Making it unverifiable. @SkidanovAlex @bowenwang1996 thoughts?

**Comment by bowenwang1996** [comment]
The light client block at height X returned by rpc is guaranteed to be in the same epoch as block X+2

**Comment by nearmax** [comment]
I see, thanks.

**Comment by SkidanovAlex** [comment]
Moreover, it is guaranteed that in each epoch such a block exists (an epoch doesn't switch unless a final block exists in it).
