### ISSUE TITLE
Near2EthClient failed with NearBridge: number of BPs should match number of approvals

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#191]
We were running bridge over night and suddenly transactions from `near-bridge` to `nearbridge` solidity contract started failing with: "NearBridge: number of BPs should match number of approvals". See the sequence of transactions and the moment it started failing here: https://ropsten.etherscan.io/txs?a=0x276d4d74dc14251c8d75ff4ae9175142e1c2254d&ps=100&p=21 The first failed transaction: https://ropsten.etherscan.io/tx/0x8fbc7ae814978a63602833cc7a36e91ca3880854df8f402f422ef226e322c83c

See the logs from the service here: https://drive.google.com/file/d/1nPx_CG62dG5mlR2t9GU-FdE2Mm2SumdQ/view?usp=sharing

Unfortunately, it does not seem to be reproducible. I have added a test here: https://github.com/near/rainbow-bridge/pull/190 It takes 2 blocks that were submitted successfully and 1 that failed to submit and resubmits it to the contract. I have even verified that the input to the contract is exactly the same by extracting the input to the transactions from etherscan. Unfortunately, it does not seem to reproduce the error: run tests from https://github.com/near/rainbow-bridge/pull/190 to reproduce.

We need to either:
* Call the current near-bridge contract deployed to Ropsten to get `last` field.
* Get the current state of the near-bridge contract deployed to Ropsten. See some hints on how it can be done: https://ethereum.stackexchange.com/questions/3353/is-there-an-easy-way-to-get-the-full-state-of-a-contract
And try replaying with it.
* Or replay all transactions that were submitted to this contract from the very beginning to recover its state.

Note. It might be possible the bug is that we are using `prev` instead of `last` here: https://github.com/near/rainbow-bridge/blob/4031aa81e9360f29b3ff05b6306d0a135469d238/libs-sol/nearbridge/contracts/NearBridge.sol#L162

@ailisp @bowenwang1996 WDYT?

**Comment by ailisp** [comment]
> Note. It might be possible the bug is that we are using prev instead of last here: 

Good point! prev=known last epoch, last=known last block, I think in the first block of the new epoch, say epoch 3, prev is still epoch 1, thus this error happens, will confirm by examine code and construct such a test to see

**Comment by ailisp** [comment]
@nearmax I think my suspect is right. in `addLightClientBlock` first check block is valid, then call `_uploadBlock`. but only in`_uploadBlock` it would update prev to "last epoch currently", so there's an off one error in the first block of new epoch, fix would be special treat first block of new epoch (e.g. epoch 3), use last (some block in epoch 2) instead of prev (epoch 1) to check approvals vs bps.
