### ISSUE TITLE
[Minor] Stop using panic!()

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#193]
Updated the description.

Currently we are using panic! in some places in Rust contracts, but it is not handled well: https://github.com/near/near-sdk-rs/issues/214. We should be more consistent and use env::panic everywhere.

**Comment by ilblackdragon** [comment]
It's not true that it's supported as well - https://github.com/near/near-sdk-rs/issues/214

**Comment by djsatok** [comment]
According to @evgenykuzyakov this is no longer relevant. See here: https://github.com/near/near-sdk-rs/issues/214#issuecomment-693629662
