### ISSUE TITLE
Add checks to Solidity contracts to make sure incorrect user input is not possible

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#195]
As reported by a user:
> Have you considered adding some checks on the TokenLocker Solidity smart contract for accountId? If a user calls lockToken with an accountId argument that's not in valid NEAR account format, their tokens will be locked but they won't be able to complete the minting procedure on the near side (and as a result they'll lose their funds). I guess you can prevent this at the UI level for the most part, but would be unfortunate to see a user lose funds due to that (e.g. when playing with the smart contracts directly from the backend). Otherwise, it might be a good idea to add a huge warning/comment in the solidity code (https://github.com/near/rainbow-bridge/blob/master/libs-sol/token-locker/contracts/TokenLocker.sol#L47) saying "accountID must be follow the  NEAR account format", and linking to the format

> Ideally you'd write this logic in Solidity (https://github.com/near/near-sdk-rs/blob/5d66300a8ec825c4b62901a7b426cf9508170d5e/near-sdk/src/environment/env.rs#L818-L846) and call it on the account id - to completely eliminate this case of user error

**Comment by djsatok** [comment]
Needs to be implemented in the frontend as a warning when entering the NEAR account
CC @paouvrard
