### ISSUE TITLE
Fun token and mintable fun token should refund when user's balance is 0

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#204]
As reported by a user:
> Should the burn function refund the sender if they burn all their balance? If I have X tokens as balance and burn them all, the env::storage_usage after the call is less. I think we should be refunded (since we initially paid for that storage when minting!). So there should be a self.refund_storage(initial_storage) above this line https://github.com/near/rainbow-bridge/blob/master/libs-rs/mintable-fungible-token/src/lib.rs#L479, along with a let initial_storage = env::storage_usage() in the first line of the burn function

This would require changes for both types of contracts in two different repos.

**Comment by nearmax** [comment]
@evgenykuzyakov the reason it was in core-contracts is because ideally, when user's balance is 0 we should remove their storage and refund tokens back.

**Comment by evgenykuzyakov** [comment]
Reassigning to @ailisp . Should be an easy fix, but maybe it worth it to add a test.

**Comment by djsatok** [comment]
This is the part of the new [fungible token standard](https://github.com/near/NEPs/blob/master/specs/Standards/Tokens/FungibleTokenCore.md) with [the storage standard](https://github.com/near/NEPs/blob/master/specs/Standards/StorageManagement.md).
