### ISSUE TITLE
Do not use default gas price in the watchdog

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#207]
As reported by a third-party:
> After looking throught the near2eth-watchdog.js script, it seems like you’re using the default gas price for calling the challenge . So if the attacker is increasing the price all the time, your transactions will not be executed during the 4-hours attack.

We should be doing the following:
* Trying the challenge with the default gas;
* If the transaction not getting executed within 5 minutes we do an exponential backoff by resubmitting the transactions with the 2x gas price;
* The backoff repeats until the transaction is accepted.

We then should argue in the comments that 10k gwei gas price should be historically sufficient for any transaction, which is achievable after about 8 backoffs (or 40 minutes of retries). We then should set our default bond to be at least 20 ETH (we need to add a comment how we computed it. @ailisp please recompute this number by estimate the gas usage of the challenge) to cover the gas costs in the worst case scenario.

**Comment by ailisp** [comment]
Take current gas price as example: 
<img width="606" alt="image" src="https://user-images.githubusercontent.com/13259400/88600305-bd342c80-d022-11ea-9fd7-7cf2f581b986.png">

Need 64 gwei to have txn executed within 5 minute (it's far longer than 5 minute with 63 gwei). Assume attack cause gas price rise and 64 gwei gas price insufficient for < 5 minute txn go through, back off will be:
```
64
128
...
64*2^7=8192 ~= 10k
```
In this worst case gas total is `5000000 * 64 + 5000000 * 128 + ... 5000000 * 8192 ~= 5e6 * 16000 = 8e10 gwei = 8 eth`. so 20 eth is enough for worst case 40min * 3 = 2 hour of use.
