### ISSUE TITLE
Service that notifies when clients stopped receiving new blocks

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#211]
We need a service that would monitor Eth2NearClient and Near2EthClient contracts and would send an alert email if they have not received blocks in expected time.

**Comment by ailisp** [comment]
assign @chefsale as discussed in meeting

**Comment by nearmax** [comment]
Setting estimate to 5 since it requires a non-trivial setup.

**Comment by djsatok** [comment]
Done in the scope of monitoring.
