### ISSUE TITLE
Run rainbow-bridge e2e test on nearcore CI

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#217]

**Comment by ailisp** [comment]
Recent results of rainbow-bridge ci on nearcore:
https://buildkite.com/nearprotocol/nearcore/builds/2685#f507586a-6b40-40f1-bd58-34e71a202b24
https://buildkite.com/nearprotocol/nearcore/builds/2729#424442e7-5a97-4bf1-9123-7bcf01586503
https://buildkite.com/nearprotocol/nearcore/builds/2716#1b9b7a2f-b887-4a1c-b5bf-b718434b57a7
https://buildkite.com/nearprotocol/nearcore/builds/2713
https://buildkite.com/nearprotocol/nearcore/builds/2712#83b2b846-062d-40a9-b2fd-7c8ce627a2b8
https://buildkite.com/nearprotocol/nearcore/builds/2709#4b83aa79-b2e8-465a-b377-c1304ce91b54
https://buildkite.com/nearprotocol/nearcore/builds/2708#7e87c761-e1aa-480f-ac4a-3cb1a6bbf3d5

Aggregate the result we have four kind:
- pass
- fail of stuck at `Block 384 is not available on the light client yet. Current height of light client is 126`, probably near-relay fails
- fail of `block 8ZHBNcqAaHagZhfPQ4f1QQ2d2fwsixoCpah1y8ftrTBU is ahead of head block FkHAbWPNSXrRjEDQv2iW7k2gUH2cHnuqudsdYHoN2qse` #222 
- fail of invalid proof
