### ISSUE TITLE
Dedicated full archival non-validating node for the bridge

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#223]
Sometimes our NEAR nodes with public facing RPC get overwhelmed with the requests and stop serving the requests including for the bridge. It takes long time for the bridge to catch up when it falls back behind as explained here https://github.com/near/rainbow-bridge/issues/184, and will still remain an issue even after we do optimizations. We need to run a dedicated full archival non-validating node for the NEAR foundation relayers to avoid competing for the RPC resources.

**Comment by ailisp** [comment]
@chefsale how do we deploy testnet node now? Could you help on this issue?

**Comment by chefsale** [comment]
Hmm, so I have seen issues with RPC nodes both on testnet and betanet, as we dont have enough of them running. Should we just spawn more RPC nodes in general instead?  Cc: @bowenwang1996 

@ailisp the adding of the testnet nodes is still the same, we didnt change that yet.

**Comment by nearmax** [comment]
@frol Shared with me links to some non-publicly facing nodes that I will be using from now on. Closing.
