### ISSUE TITLE
Implement "initialized" to NEAR contracts

### ISSUE THREAD

**Issue by Kouprin** [near/rainbow-bridge#270]
According to @ailisp (https://github.com/near/rainbow-bridge/pull/264#discussion_r468753310) we need a method which says that the contract is actually deployed to the NEAR. It seems we already have `initialized()` for some contracts.

However there may be a standard nearlib way to check the contract for its deployment state. The task is:
1. Implement `initialized()` in NEAR contracts.
2. Update `index.js status` with checking `initialized()` method.

**Comment by nearmax** [comment]
There is no standard way. It is not a nearlib restriction, it is a restriction of the runtime.

**Comment by Kouprin** [comment]
> There is no standard way. It is not a nearlib restriction, it is a restriction of the runtime.

The task is updated.

**Comment by djsatok** [comment]
Already implemented
