### ISSUE TITLE
Bridge CI is broken

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#271]
See https://buildkite.com/nearprotocol/rainbow-bridge/builds/560

Also, are we running bridge CI in nearcore?

**Comment by Kouprin** [comment]
> Also, are we running bridge CI in nearcore?

There is `buildkite/nearcore/rainbow-bridge-test` in nearcore that's running in CI.

**Comment by Kouprin** [comment]
please do `test _challege_ with near watchdog` -> `test challenge with near watchdog`

**Comment by ailisp** [comment]
> See https://buildkite.com/nearprotocol/rainbow-bridge/builds/560

This is a know issue, observe there's only 6 logs (no near-watchdog), the issue is index.js start near-watchdog didn't start watchdog, it happens occasionally on ci but not reproducible locally. Still investigating it

**Comment by nearmax** [comment]
@ailisp I was not able to find bridge running on the nearcore CI. Is it running on nearcore CI, could you send here a link?

**Comment by ailisp** [comment]
For example https://buildkite.com/nearprotocol/nearcore/builds/3085#937b0394-79a9-4032-a8d6-03a04ed5d9eb in a latest PR: https://github.com/nearprotocol/nearcore/pull/3159

**Comment by nearmax** [comment]
Thank you!
