### ISSUE TITLE
Replace eth-util-lite with ethjs-util

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#286]
`eth-util-lite` is an unpopular fork of a popular `ethjs-util`. We need to use the popular version of the library.

**Comment by ailisp** [comment]
I think either of them are not popular. ethjs-util hasn't been updated for two years, eth-util-lite about a year and a half. And we're using our fork of eth-util-lite and eth-object depends on it, we've carefully adjust a few web3 vs eth rpc difference to make it work correctly which is not available in any of these libs. I suggest we keep maintain our fork, and if really would find a popular lib, rewrite these utils depends on web3 and ethereumjs, the only two official libs.

**Comment by djsatok** [comment]
Some additional research needed
