### ISSUE TITLE
Add Rainbow-bridge to Nayduck

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#287]
We need to add existing rainbow-bridge to Nayduck and run on regular cadence. This should be used mostly for heavy e2e tests. This should include tests that verify proofs to all Ethereum events starting from the last Ethereum fork. And it should include tests that verify proofs for all NEAR execution outcomes starting from the last NEAR fork of the Mainnet.

**Comment by djsatok** [comment]
Bridge is deployed to Nayduck, other parts of this issue are in #288 #289 #290 #291
