### ISSUE TITLE
[Tracking Issue] Upgradability

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#298]
We need to implement self-upgradability controlled by NEAR validators as described here in this post https://near.org/blog/eth-near-rainbow-bridge/ We should use one of the proxy patterns for it, both for NEAR and Ethereum contracts.

**Comment by nearmax** [comment]
Please consider the following Proxy Patterns: https://blog.openzeppelin.com/proxy-patterns/

**Comment by nearmax** [comment]
More info on upgradability patterns: https://ethereum.stackexchange.com/questions/75890/pros-and-cons-of-smart-contract-upgradable-patterns

**Comment by ilblackdragon** [comment]
On the NEAR side we can leverage next pattern (which is similar to Ethereum):

```
struct Upgradable {
   owner: AccountId
}
impl Upgradable {
  /// Updates code and calls migration method if not empty?
   pub fn upgrade(&mut self, code, migrate_method_name: &str, args: Vec<u8>) { assert_eq!(env::predeccesor_id(), self.owner); // promise to itself to call DeployContract }
   pub fn change_owner(&mut self, new_owner) ...
}
```

We can possibly split this into Ownable and Upgradable that requires Ownable.

This way we can deploy already with an account we control, and then change owner to an account that is voted by our validators.

It also decouples the voting from bridge itself, which is cleaner and allows us to test it separately even on MainNet to check that validators have the tools to vote.

**Comment by djsatok** [comment]
There's a great overview of the upgradability patterns [here](https://blog.openzeppelin.com/the-state-of-smart-contract-upgrades/).

**Comment by ilblackdragon** [comment]
Posted a proposal for standard for NEAR here - https://github.com/nearprotocol/NEPs/pull/123

**Comment by djsatok** [comment]
PoA upgradability is implemented.
Outdated, discussions should happen aligned with OKRs Q1 2021.
