### ISSUE TITLE
Test unreliable Ethereum RPC

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#302]
We need to have and e2e test that would spin up Ethereum  node make sure that it has a highly unreliable RPC (e.g. by using linux kernel-level filters to drop packages) and make sure that relays are able to function and the transfers are able to be completed. In the past we had lots of issues with unreliable RPC breaking bridge code.

**Comment by djsatok** [comment]
At the moment we decided to run our own full Ethereum nodes
