### ISSUE TITLE
nearcore bridge test CI does not save artifacts

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#320]
Observe the following bridge build run: https://buildkite.com/nearprotocol/nearcore/builds/3291#7aa95347-5171-48ff-8199-568c37955ad6

Unfortunately, all artifacts are empty. While at least some of them should be non-empty:
![image](https://user-images.githubusercontent.com/35039879/91100999-10e26780-e61b-11ea-993f-dab95e74c57e.png)

This prevents debugging failed CI builds.

**Comment by ailisp** [comment]
Fixed
