### ISSUE TITLE
Update the instructions in README.md to account for the split

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#326]
The current README.md contains instructions on how to start and use the bridge locally and how to use bridge running on testnet, but these instructions are outdated. We need to do the following things:
- [x] Update instructions in README.md that start local bridge to account for the changes introduced by the split;
- [ ] Update instructions in README.md on how to use bridge running on the testnet.

**Comment by ailisp** [comment]
First part is done in #321 For second part do you have a short note on how did you deploy our bridge in testnet & bridge services?

**Comment by nearmax** [comment]
Done https://github.com/near/rainbow-bridge-cli/blob/master/README.md the last piece, it however, does not include instructions on how to deploy connectors and run transfers because I got blocked by https://github.com/near/rainbow-bridge-cli/issues/330

**Comment by djsatok** [comment]
Outdated
