### ISSUE TITLE
Publish npm package in ci

### ISSUE THREAD

**Issue by ailisp** [near/rainbow-bridge#327]
As now we have four npm packages, it's inconvenient and error prune to publish manually, so it's ideally to publish this four repos as part of buildkite pipelline:
- near/rainbow-bridge-lib
- near/rainbow-bridge-sol
- near/rainbow-bridge-rs
- near/rainbow-bridge-cli

TODO:
- [ ] create a new npm user
- [ ] add a hook that starts deployment process automatically right after changing the version, but only in master branch

**Comment by ailisp** [comment]
Some resource online: https://github.com/uber-workflow/buildkite-npm-deploy

**Comment by djsatok** [comment]
Outdated
