### ISSUE TITLE
Design and MVP of testing infrastructure for Bridge

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#350]
The new testing infrastructure of the bridge is discussed here: https://github.com/near/rainbow-bridge-cli/issues/338 / https://github.com/near/rainbow-bridge-cli/issues/339 . This issue tracks only two work items:
- [ ] Design of the new testing infrastructure -- @Kouprin needs to finalize the design and make sure everyone is onboard;
- [ ] MVP implementation of the design. Fully completing https://github.com/near/rainbow-bridge-cli/issues/338 and https://github.com/near/rainbow-bridge-cli/issues/339 might not be feasible within two weeks, but we need to have some core of the testing infrastructure implemented.

@Kouprin estimated this work to take 5 days.

**Comment by chefsale** [comment]
Please add a sanity integratoin test for versioning of the npm package, install the package locally and just 
 try to run the bridge: https://nearprotocol.pagerduty.com/postmortems/163b2cc1-023b-443e-4012-434dca4a4805

**Comment by mfornet** [comment]
Done in https://github.com/near/nearcore/pull/3658
