### ISSUE TITLE
Design and MVP of new Bridge CLI and Lib API

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#351]
Based on https://github.com/near/rainbow-bridge-cli/issues/338#issuecomment-691173698 we need to revisit the interface of CLI (how it works with command line arguments, environment variables, config) and come up with separation between CLI and the library. Currently, library is still using the config object, which is very specific to CLI and might not be convenient to work with from the browser. This issue includes the following work items:
- [ ] Evaluating CLI options on Rust and discussing them with @frol -- 0.5 day
- [ ] Rewriting the config -- 1-3 days
- [ ] Understanding CI and deployment process -- 1 day

Assigning 5 days to this work item.

**Comment by djsatok** [comment]
The discussion #482 is created
