### ISSUE TITLE
Make sure our code keeps working when there are multiple shards

### ISSUE THREAD

**Issue by abacabadabacaba** [near/rainbow-bridge#356]
Currently, our code makes certain assumptions that are valid when there is only one shard but not when there are multiple shards. Before using the bridge with multi-sharded NEAR blockchain, we should check our logic for generating and verifying proofs regarding NEAR blockchain so that it handles the case of multiple shards correctly.

**Comment by djsatok** [comment]
@abacabadabacaba, can you please elaborate on the assumptions?
