### ISSUE TITLE
[Tracking issue] Test Rinkeby and local setup

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#364]
Before @frol can start working on the bridge issues, he needs to try using bridge on Rinkeby and locally following these instructions:
* https://github.com/near/rainbow-bridge-cli#using-bridge-on-testnet
* https://github.com/near/rainbow-bridge-cli#deploying-and-using-locally

**Comment by frol** [comment]
*I am going to track my journey here (potentially convert those items into PRs or separate issues).*

1. "Make sure you are using Node with version <=13", I am pretty sure the minimum supported by near-api-js Node version is 12.x, so the statement should be adjusted
2. Doing `rainbow prepare` I hit: `fatal: not a git repository (or any of the parent directories): .git` right after `neard` got compiled (the error is unclear what exactly was expected to be a git repo)

**Comment by frol** [comment]
Closing this stale issue. The discrepancies in the README were submitted as a PR #426
