### ISSUE TITLE
Propose the names for the components and repos + descriptions

### ISSUE THREAD

**Issue by Kouprin** [near/rainbow-bridge#374]
Please post in comments your suggestions.

**Comment by Kouprin** [comment]
very first iteration

**repos:**
https://github.com/near/rainbow-token-connector - there are may be several token connectors, I suggest to rename to token-connector-erc20-nep21, no rainbow needed
https://github.com/near/rainbow-bridge-frontend -> split into token-connector-browser and token-connector-example

**npm packages**
https://www.npmjs.com/package/rainbow-bridge-cli -> rainbow-bridge
https://www.npmjs.com/package/rainbow-bridge-lib -> [deprecated]
https://www.npmjs.com/package/rainbow-bridge-sol -> rainbow-bridge-eth-contracts
https://www.npmjs.com/package/rainbow-bridge-rs -> rainbow-bridge-near-contracts
eth2near block relay -> rainbow-bridge-eth2near-block-relay
ethash -> rainbow-bridge-eth2near-ethash
near2eth block relay -> rainbow-bridge-near2eth-block-relay
watchdog -> rainbow-bridge-near2eth-watchdog
rainbow bridge client contract interfaces -> rainbow-bridge-contract-interfaces
rainbow bridge config -> rainbow-bridge-config

**Comment by frol** [comment]
@Kouprin Thanks for giving this a shot! It helps me a lot.

> https://github.com/near/rainbow-token-connector - there are may be several token connectors, I suggest to rename to token-connector-erc20-nep21

Great point that we should be specific about which assets we bridge

> no rainbow needed

Doesn't it rely on the rainbow spec? I guess, it is better from the discoverability point of view to have "rainbow" in the name: "rainbow-token-connector-erc20-nep21" while somewhat long, helps to clearly identify the context.

> https://github.com/near/rainbow-bridge-frontend -> split into token-connector-browser and token-connector-example

I would like to draw my path of thinking here:

* I put two names side-by-side: "rainbow-token-connector-erc20-nep21" and "rainbow-token-connector-browser"
* I observe that it is not intuitive how "erc20-nep21" and "browser" are releated. They are, in fact, are quite different entities, so they should not be named in such a way that may break intuition.
* Either "rainbow-token-connector-erc20-nep21" or "rainbow-token-connector-browser" should be renamed to have a clear prefix indicating its kind. "rainbow-token-connector-erc20-nep21" is the implementation of the connector deployed on the chains, I think it is fine to name it that way. "rainbow-token-connector-browser" is the client to the APIs provided by the "rainbow-token-connector-erc20-nep21" (and possibly other connectors). We have a precident with "near-api-js" being the client to nearcore JSON RPC, so I think we can name it "rainbow-token-connector-api-js"
* but I still don't like that they share the same prefix ("rainbow-token-connector").
* going back, I think we may consider "rainbow-token-connector-impl-erc20-nep21", "rainbow-token-connector-backend-erc20-nep21" -- I really don't like either of those, so it would be great to generate more options.

> https://www.npmjs.com/package/rainbow-bridge-cli -> rainbow-bridge

`-cli` seems to be a safe bet for me. Having `near-cli`, `gulp-cli`, `webpack-cli`, `ember-cli`, I would strongly consider keeping `-cli`.

> https://www.npmjs.com/package/rainbow-bridge-lib -> [deprecated]

Agree. The only need for it was the thing that is now "rainbow-token-connector-api-js" (see above).

> https://www.npmjs.com/package/rainbow-bridge-sol -> rainbow-bridge-eth-contracts

How many contracts do we have for eth? I assumed we only had one for bridge and one+ for token connectors. Why do we need them packaged into npm package? Is it just the way we want to manage our releases? 

> https://www.npmjs.com/package/rainbow-bridge-rs -> rainbow-bridge-near-contracts

Same questions as above

> eth2near block relay -> rainbow-bridge-eth2near-block-relay
> ethash -> rainbow-bridge-eth2near-ethash
> near2eth block relay -> rainbow-bridge-near2eth-block-relay

:+1: 

> watchdog -> rainbow-bridge-near2eth-watchdog

Is there anything special about the watchdog?
> rainbow bridge client contract interfaces -> rainbow-bridge-contract-interfaces

Well, Rust packages need to be released to crates.io. Do solidity contracts have their package manager? Is there any use for this npm package?

> rainbow bridge config -> rainbow-bridge-config

Do we need a separate package for it? I would assume it to be part of internal implementation of "rainbow-bridge-cli" up until we decide to make the tool usable as a library, and even then it should be just part of the library.

**Comment by Kouprin** [comment]
I guess it's mostly done.
