### ISSUE TITLE
Unblock Hackathon evaluation

### ISSUE THREAD

**Issue by Kouprin** [near/rainbow-bridge#380]
We need to finalize the Hackathon questions and get rid of deprecated version of architecture ASAP. @nearmax is the best person who knows how to restart current version of Bridge at Rinkeby and unblock the evaluation.

Transferring of Rinkeby handling to @Kouprin is out of the current milestone.

**Comment by nearmax** [comment]
> Transferring of Rinkeby handling to @Kouprin is out of the current milestone.

I suggest we prioritize it and do it within the next week.
