### ISSUE TITLE
Choose a framework for Ethereum contracts

### ISSUE THREAD

**Issue by abacabadabacaba** [near/rainbow-bridge#383]
Currently we are using [Truffle](https://www.trufflesuite.com/) for testing Ethereum contracts and a custom Bash script for building them. Truffle is too inflexible for our needs. For example, it is difficult to make it work with contract code that is generated at build time (and we want to do this with Ed25519 code). There are [other frameworks](https://ethereum.org/en/developers/docs/frameworks/) for Ethereum contracts, so we should try to find the one most suitable for us.

**Comment by djsatok** [comment]
@abacabadabacaba @sept-en What do you think of this? Should we close this issue?

**Comment by abacabadabacaba** [comment]
We switched to Hardhat in #517, so closing this.
