### ISSUE TITLE
Proving Ethereum events in EthOnNearClient that happened in the past.

### ISSUE THREAD

**Issue by mfornet** [near/rainbow-bridge#389]
The current Eth Light Client implementation as a contract in NEAR only store last 46k blocks which is roughly 7 days of blocks. This means that any event that happened more than 7 days ago can't be proved in the NEAR side, and won't be able to be proved in the future. However, in the NEAR Light client on Ethereum any event can be proved, because each block maintains not only its block hash, but the root of the merkle-tree of all blocks.

The same strategy can be used in the Eth Light Client, to enable use cases that relies on transactions that spans over periods longer than 7 days. One important downside of this approach, is that it will become a client side responsability to maintain the merkle-path to submit a proof. Since this is for most common cases unacceptable I propose a hybrid between the two approaches.

We maintain the last 46k blocks (as we are doing in the current design), and every (let's say) 23k blocks we also submit the root of the merkle-tree of all the blocks. Notice that verifying the root of the merkle-tree might be an expensive operation in a contract, but we actually don't need to submit it too frequently, we just need to submit before exhausting all 46k last blocks since last merkle root submission.

This change will not affect any of our current use cases, and will remove the restriction that only transactions that happened in the last 7 days can be proved.

Moved from https://github.com/near/rainbow-bridge-rs/issues/9

**Comment by mfornet** [comment]
This will not longer be a limitation on version 2 of the bridge.

**Comment by djsatok** [comment]
Will be implemented in v2.0
