### ISSUE TITLE
Web3 gets stuck

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#39]
When initializing Web3 in the node.js app it gets stuck and does not let the app to finish.

To reproduce, navigate into `rainbow-bridge/rainbowup` and execute:
```bash
python3 main.py cleanup
python3 main.py prepare
python3 main.py test
```
Observe that the last command simply does not finish, this is because running `node index.js extract_proof` does not finish. The expected behavior is that it finishes.

---

To diagnose you can pass paths to the local source code to facilitate debugging, e.g.:
```bash
python3 main.py cleanup --source=/Users/maksymzavershynskyi/Projects/rainbow-bridge --nearcore_source=/Users/maksymzavershynskyi/Projects/nearcore
python3 main.py prepare --source=/Users/maksymzavershynskyi/Projects/rainbow-bridge --nearcore_source=/Users/maksymzavershynskyi/Projects/nearcore
python3 main.py test --source=/Users/maksymzavershynskyi/Projects/rainbow-bridge --nearcore_source=/Users/maksymzavershynskyi/Projects/nearcore
```
After `python3 main.py test` hangs you can observe the printed env variables: `ETH_NODE_URL` and `TX_HASH` and use them to debug the node.js app manually:
* Navigate into `environment` and run: `ETH_NODE_URL='ws://localhost:9545' TX_HASH='0x640733ce51f6205de2444a57cf22e43532edfa3279a3502b2bf149dc7fcca1db' node index.js extract_proof`

If you run node.js app in the debug mode you will see that after `this.web3 = new Web3(ethNodeURL)` is initialized in `EthProofExtractor` and `debugPrint` is successfully executed the code still waits in `this.web3 = new Web3(ethNodeURL)`.

**Comment by ailisp** [comment]
I'm getting this error before hitting node index.js extract_proof:
```
error Command failed with exit code 1.                                                                                 
Traceback (most recent call last):
  File "main.py", line 267, in <module>
    arg_parser = RainbowupArgParser()
  File "main.py", line 78, in __init__
    getattr(self, self.args.command)()
  File "main.py", line 235, in test
    '--no-interactive'], cwd=os.path.join(self.args.source, 'libs-sol/emitter'))
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['yarn', 'run', 'oz', 'deploy', 'Emitter', '--kind', 'regular', '--network', 'development', '--silent', '--no-interactive']' returned non-zero exit status 1.
```

**Comment by ailisp** [comment]
yarn run oz deploy Emitter doesn't give much useful information. Drop `--silent` I got this in stderr
```
b"- Nothing to compile, all contracts are up to date.\n- OpenZeppelin file .openzeppelin/project.json not found. Run 'openzeppelin init' first to initialize the project.\nerror Command failed with exit code 1.\n"
```
Seems I need to install openzeppelin locally first?

**Comment by ailisp** [comment]
Solved. need to `yarn` in rainbowup/libs-sol/emitter, will add it to prepare

**Comment by ailisp** [comment]
Update: as of today, main.py test is run test_ethprover instead, and it's not stuck on web3 but it still stuck after finish tests

**Comment by nearmax** [comment]
> Update: as of today, main.py test is run test_ethprover i

Correct, it is not stuck on the line that creates Web3 object, but the script is getting stuck, overall, because AFAIU Web3 object is holding an open socket that prevents the script from finishing.

**Comment by nearmax** [comment]
Fixed.
