### ISSUE TITLE
Rainbowup: Dockerize relayers

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#40]
Currently rainbowup starts relayers natively as node.js apps. However, for the production setup we need to have a way to start them as docker containers that we can start and restart easily. It might be sufficient to create only one Docker image `rainbow_environment` that encapsulates `rainbow-bridge/environment` node.js app. Then depending on the command passed as the command line flag this docker image can start as an EthRelayer or as a NearRelayer.

**Comment by ailisp** [comment]
closed via #51
