### ISSUE TITLE
Nayduck basic integration

### ISSUE THREAD

**Issue by Kouprin** [near/rainbow-bridge#410]
- [ ] Pytest lib for Bridge testing
- [ ] Running Ganache
- [ ] Init ETH contracts
- [ ] Init NEAR contracts
- [ ] Running Near2Eth Relay
- [ ] Running Eth2Near Relay
- [ ] Sending transactions
- [ ] Using config
- [ ] Sanity test

**Comment by mfornet** [comment]
Done in https://github.com/near/nearcore/pull/3658
