### ISSUE TITLE
[Bug] Watchdog should ignore skipped signatures

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#418]
Since we altered the behavior of NearOnEthClient when it verifies the signatures: https://github.com/near/rainbow-bridge/blob/master/contracts/eth/nearbridge/contracts/NearBridge.sol#L120 it is not breaking the watchdog that expects `checkBlockProducerSignatureInHead` to never fail as long as it stays within the range of the signatures: https://github.com/near/rainbow-bridge/blob/master/near2eth/watchdog/index.js#L68

**Comment by abacabadabacaba** [comment]
What's the bug? Currently, `checkBlockProducerSignatureInHead` will revert if the signature is skipped, and the check `!e.reason || !e.signature` is specifically to ignore reverts (but not other exceptions).

**Comment by nearmax** [comment]
@abacabadabacaba , it seems it was the intention, but when I run watchdog as is it crashes when it reaches skipped signature. Something does not work as intended.

**Comment by SkidanovAlex** [comment]
> it seems it was the intention, but when I run watchdog as is it crashes when it reaches skipped signature. Something does not work as intended.

Can you provide more information about the failure? The stack trace?

**Comment by mfornet** [comment]
Solved on #454
