### ISSUE TITLE
Implement ED25519 verification in Solidity

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#42]
We need to be able to verify ED25519 in Solidity. The implementation does not have to be efficient.
@abacabadabacaba kindly agreed to help @k06a with cryptographic nuances.

**Comment by nearmax** [comment]
@abacabadabacaba @k06a Do I understand correctly that this is done? Closing it, please reopen if it is not.

**Comment by k06a** [comment]
@abacabadabacaba how things going with new version with fix you mentioned recently?

**Comment by abacabadabacaba** [comment]
Looks like the code is good now, so closing.

**Comment by nearmax** [comment]
Thank you!
