### ISSUE TITLE
cli uses 2-months old token contracts with bug

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#421]
When @mfornet was doing the hot fix of token connector we noticed that once we compiled the contracts the compiled contract contained modifications that were not done by @mfornet : https://github.com/near/rainbow-token-connector/pull/14/files#diff-e4f68faad20d6a02615bb6cd48ba4c5a3eb0cc5c445875a767f486a314156c19R532 You can see that the bug fix added `shift(data, 20)`.

This is because token connectors were not recompiled for 2-3 months, even though the changes were done to the code during this time. 

Also, we CLI is pointing to 2-months old token connector commit: https://github.com/near/rainbow-bridge/blob/master/cli/package.json#L37 We probably should replace github dependencies both in `rainbow-bridge` and `rainbow-token-connector` repos with npm packages.

**Comment by mfornet** [comment]
Tracking on #458
