### ISSUE TITLE
Extract proofs creating scripts

### ISSUE THREAD

**Issue by djsatok** [near/rainbow-bridge#432]
At the moment the only way how the bridge can be used is through CLI. CLI is intentionally abstracting complicated calls to the higher level, making bridge usage simpler. However, fails in the CLI calls execution may not be directly connected with contracts bugs, but with the CLI implementation. The absence of lower interface of interaction with the bridge automatically lead to several problems:
1. There's no clear way for a user to finalise the transfer if it was interrupted by the CLI bug
2. No separation of concerns. Execution failures may not directly lead to the level where the problem occurred.
3. There's no clear way how to run complicated e2e tests that are *not* following the CLI logic
4. A user is passing his private keys to some (really complex) script and is not controlling actual transactions that are signed. For some users this would be a major concern for usage of the CLI.

Though the CLI script is rather simple for ERC-20 transfers. ERC-20 -> NEP-21 transfer has multiple steps (similar logic works within transfer back):

1. Ethereum transaction. [Approve ERC-20 transfer](https://github.com/near/rainbow-bridge/blob/master/testing/transfer-eth-erc20/to-near.js#L347-L365).
2. Ethereum transaction. [Lock tokens](https://github.com/near/rainbow-bridge/blob/master/testing/transfer-eth-erc20/to-near.js#L366-L376).
3. Custom script. [Extract event proof](https://github.com/near/rainbow-bridge/blob/master/testing/transfer-eth-erc20/to-near.js#L377-L384).
4. Custom script. Wait for enough confirmations in `EthOnNearClient`.
5. NEAR transaction. [Deposit token to destination address](https://github.com/near/rainbow-bridge/blob/master/testing/transfer-eth-erc20/to-near.js#L392-L398).

Stages 1, 2 can be passed knowing all the inputs to CLI (contract addresses, user addresses, private keys, etc.) through [geth](https://github.com/ethereum/go-ethereum) (even in a light client mode). Stage 5 can be passed through near-cli. Stage 4 is just waiting so can be substituted to recommendations on timings & checking view calls to NEAR blockchain (or Ethereum blockchain for opposite transfer).

The only stage that can not be passed easily is 3. Within this stage CLI collects the data from Ethereum full nodes (from RPC) and does not that simple [assemblin MPT proof](https://github.com/near/rainbow-bridge/blob/884c55cff8e9dfd85a6418496516e05ff2a4e54c/eth2near/eth2near-block-relay/eth-proof-extractor.js#L30-L44), which cannot be simply done from shell.

The solution to all above mentioned problems is to extract **proof creation scripts** and make them available through the CLI of the bridge.

**Note**: proof creation scripts are literally the only pieces that are needed to the end users from the core bridge. All the other interfaces / methods / endpoints can be completely hidden. Perhaps, this means that proof creation should be the only calls available in `bridge-cli` (if we don't think we should fit in it tools for devs), other scripts should be moved to `connector-cli`.

Extracting proof scripts would highly simplify the understanding of way how the bridge is operating for early bridge users.

**Comment by djsatok** [comment]
Step 5 would require signing a BLOB by `near-cli`. @vgrichina started the PR on this: https://github.com/near/near-cli/pull/614. Really appreciate his help!

**Comment by mfornet** [comment]
Step 3 is already implemented in: https://github.com/near/rainbow-bridge/blob/master/cli/index.js#L570-L580

Use it with:

```
node cli/index.js eth-to-near-find-proof <locked_event>
```

**Comment by djsatok** [comment]
Done in https://github.com/djsatok/bridge-testing/
CLI requires refactoring, no need to add scripts to CLI.
