### ISSUE TITLE
Remove unused components from old mintable-fungible-token

### ISSUE THREAD

**Issue by mfornet** [near/rainbow-bridge#462]
This repository currently contains several components relevant to the deployment and the execution of the token-connector. Most of them are related to an old version using custom [mintable-fungible-token](https://github.com/near/rainbow-bridge/tree/master/contracts/near/mintable-fungible-token). See also #420 for unused commands that our cli is supporting.

All this components should be detected and removed from this repository. In case some of them are relevant to run some `cli` commands interacting with the token-connector or for `tests`, the logic should be imported directly from [token-connector](https://github.com/near/rainbow-token-connector/).

To remove:
- Contracts on Near side.
- Contracts on Ethereum side.
- Cli commands that are no longer required.

**Comment by sept-en** [comment]
I will take a look at this next week.
