### ISSUE TITLE
Check the local deployment part of the README.md

### ISSUE THREAD

**Issue by djsatok** [near/rainbow-bridge#467]
We need to make sure that the current readme.md is providing the correct guidelines for the local deployment of the bridge.
One need:
- [ ] Run the local NEAR node and Ganache
- [ ] Deploy core bridge contracts (light clients, provers)
- [ ] Deploy relayers 
- [ ] Check that relayers are sending transactions; transactions are normally executed
- [ ] Deploy rainbow-token-connector
- [ ] Create an ERC-20 token in Ganache (e.g. [this one](https://github.com/uzyn/ERC20-TST) or any other).
- [ ] Check the ERC-20 transfer to NEAR and back

The README.md should be updated, so an external person can do this walkthrough.

**Comment by sept-en** [comment]
I will take a look.
