### ISSUE TITLE
Add logging to the `add_block_header` method of Eth Client to show the current synching height 

### ISSUE THREAD

**Issue by djsatok** [near/rainbow-bridge#476]
At the moment there's no simple way to check the height of the Ethereum blockchain that is synced. See [here](https://explorer.testnet.near.org/transactions/Fum1r9mq2PBnN8K5SLjTzGEgo7iBdDckQjuUTXUeohvW).

The method receives [block header in RLP and DAG nodes](https://github.com/near/rainbow-bridge/blob/master/contracts/near/eth-client/src/lib.rs#L202). The height of the block is what is interesting in this data, but it's impossible to see it in the explorer.

Something like
```
log!("Current block height is {}", header.number);
```
should be added in the end of the method.

**Comment by mfornet** [comment]
This information is currently exposed in the contract: 

https://github.com/near/rainbow-bridge/blob/beta/contracts/near/eth-client/src/lib.rs#L167

Relayers also expose this information as metrics:

https://github.com/near/rainbow-bridge/blob/beta/eth2near/eth2near-block-relay/index.js#L72

To check current syncing height either check grafana dashboard, or directly consume exposed metrics in:

http://35.235.76.186:8002/metrics
