### ISSUE TITLE
Add test to Eth2NearProver and proof extractor

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#48]
Upon calling `rainbowup test` it should do the following:
* Spin up the near node;
* Start Eth2NearRelayer and make it submit headers from Ethereum mainnet;
* Then in the loop, take a block from Ethereum mainnet and for each receipt (transaction outcome), for each log in the transaction outcome create a proof and submit it to the prover, make sure the prover successfuly verifies that the proof is correct.

**Comment by nearmax** [comment]
Done

**Comment by SkidanovAlex** [comment]
Attach the PR in which it is done to the issue?

**Comment by nearmax** [comment]
https://github.com/near/rainbow-bridge/pull/51
