### ISSUE TITLE
CI tests for Eth2NearClient

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#58]
Currently we can test our EthProver in the following way.

# Current way of testing Eth2NearClient

Run in the first terminal:
```bash
python3 main.py cleanup --source=/Users/maksymzavershynskyi/Projects/rainbow-bridge --nearcore_source=/Users/maksymzavershynskyi/Projects/nearcore
python3 main.py prepare --source=/Users/maksymzavershynskyi/Projects/rainbow-bridge --nearcore_source=/Users/maksymzavershynskyi/Projects/nearcore
python3 main.py run --eth_node_url=wss://mainnet.infura.io/ws/v3/<project_id> --source=/Users/maksymzavershynskyi/Projects/rainbow-bridge --nearcore_source=/Users/maksymzavershynskyi/Projects/nearcore
```
This will shutdown any services that are currently running and will cleanup any temporarily files that were created. Then it will compile the contracts, and finally it will start: local near node and the relayer that will be submitting blocks from Eth mainnet to near node.

Observe multiple blocks being successfully submitted to the Eth2NearClient.

# Better way of testing Eth2NearClient

Our tests should be hermetic and runnable on CI. Instead of getting blocks from Ethereum mainnet we need to dump a large number of them into a file in some test directory and then run Eth2NearClient contract on them verifying that it can successfully verify and accept all of them.

**Notes**

* Please ask @nearmax for <project_id> for infura;
* Please make sure you are synced with @chefsale who is working on restructuring project so that it uses systemd and docker compose. He is also replacing Python code with JS.

**Comment by ailisp** [comment]
> Please make sure you are synced with @chefsale who is working on restructuring project so that it uses systemd and docker compose. He is also replacing Python code with JS.

I'll wait docker-compose ready to have a new solid base for a new test script/pipeline. Also is there specific reason to use systemd over rainbowup, and docker compose over helm charts? @chefsale

**Comment by nearmax** [comment]
@ailisp  Would you be able to add the above mentioned test though? It seems to be orthogonal to docker compose/systemd effort?

**Comment by ailisp** [comment]
@nearmax I'm not certain about the test, here is what i thought (correct me if i'm wrong and with more details)
> dump a large number of them into a file in some test directory and then 

This seems to require modify main.py run --eth_node_url=<web3url> to dump blocks (instead of fetch and submit to contract, since python -> js is happening, I'd like to work on the nodejs script to do this.

> run Eth2NearClient contract on them verifying that it can successfully verify and accept all of them.

This seems need the running Eth2NearClient, which will change when it launches as docker-compose container, I can then submit to Eth2NearClient or extend Eth2NearClient container to accept a collected file from above step and run.

**Comment by nearmax** [comment]
> This seems to require modify main.py run --eth_node_url= to dump blocks (instead of fetch and submit to contract, since python -> js is happening, I'd like to work on the nodejs script to do this.

You can call nodejs script directly, just lookup what env variables the Python code uses to pass to the nodejs script and call this script directly. You would have to write a code in JS to dump the blocks instead of submitting them to the contract.

> This seems need the running Eth2NearClient, which will change when it launches as docker-compose container, I can then submit to Eth2NearClient or extend Eth2NearClient container to accept a collected file from above step and run.

This can be tested without running Eth2NearClient. You can either write a Rust unit test or a unit test using `near-runtime-standalone`. Checkout the contract tests implemented here: https://github.com/near/initial-contracts/tree/master/lockup/tests

**Comment by chefsale** [comment]
I decided to use https://pm2.keymetrics.io/. This seems like a good solution for spawning all the processes needed. This won't work for docker because, it's one process per image. But I will create a docker image for every single process in the bridge and use docker compose in case somebody want to use that instead of the native node implementation. cc: @ailisp @nearmax

**Comment by ailisp** [comment]
I like pm2 too and it's neat for multiple nodejs microservices.
Also for docker compose it isn't production ready, I think we should either use helm charts or docker swarm, but obviously k8s is more popular than docker swarm. And docker-compose gives you a faster local setup, but it's isn't a lot difficult to use a helm chart and helm gives you production ready k8s configurations.
On mac:
- docker-compose comes with docker-desktop, docker-compose up
- minikube comes with docker-desktop too, brew install helm and helm apply
On linux:
- you need install docker-compose (doesn't come with docker) and minikube, ubuntu also comes with a neat official support minik8s.

**Comment by chefsale** [comment]
Hmm, running docker swarm seems like an overkill for this use case and docker compose should be production ready. Maybe we could look into using helm, but both docker swarm and kubernetes are made for running big scale deployments and orchestrate across machines. At this point I don't think we need that, if we are able to provide PM2 and docker compose to run containers independently on together on single host people can use different deployment systems, not limited to these to but AWS ECS, Azure, etc.

**Comment by chefsale** [comment]
As well, you can run composed docker images on kubernetes as well easily: https://stackoverflow.com/questions/37845715/can-kubernetes-be-used-like-docker-compose

**Comment by ailisp** [comment]
It makes sense but i'm afraid we'll soon need to scale rainbow-bridge on more than one instance.
- For production: docker-compose is only good for one machine
- For local development, single machine:
  - For user: both helm and docker-compose is a one line spin up all services, helm comes with live upgrading part or all service, quickly live update enviroment var / config on one service, docker-compose cannot, so a little better user experience
  - For us: helm charts is harder to write than docker-compose, need at least two file for each service (one deployment + one service yaml) and parameterize all environment var.

Also, in last if we have docker-compose, we still going to need helm chart for deploying bridge for clients, if we have helm chart we don't need docker-compose since even local dev experience is better

**Comment by chefsale** [comment]
So, my concern is that helm is kubernetes only, but docker compose can be ran everywhere. So, if you run only docker compose up than it is only single machine, but all clouds enable you to run it on  a container-orchestration system. 

For more reference here:
AWS:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html

Azure:
https://docs.microsoft.com/en-us/azure/cognitive-services/containers/docker-compose-recipe

Kubernets based cloud: https://stackoverflow.com/questions/37845715/can-kubernetes-be-used-like-docker-compose

Same for all the others, but the problem is helm is kubernetes only which is a more specialized tool, so in my opinion we should stick to that.

**Comment by ailisp** [comment]
> As well, you can run composed docker images on kubernetes as well easily: https://stackoverflow.com/questions/37845715/can-kubernetes-be-used-like-docker-compose

This isn't a "one line import" solution, you still need to tweak disks, env vars, and you need add things like ingress, which isn't easily ready to use and your updating to each of those, without helm, isn't reserved to one command rollback, it's not a good practice to skip helm when use k8s.

> Same for all the others, but the problem is helm is kubernetes only which is a more specialized tool, so in my opinion we should stick to docker compose.

docker-compose is not designed for deploy in a production, kubernetes gives you much more, like health check, restart died services, rolling update, scale each microservice separately manually or automatically based on some metric, atomic deploy and rollback history, etc for free. I don't think we should run rainbow-bridge should be run production as docker compose, it's much less robust

**Comment by ailisp** [comment]
> AWS:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html
Azure:
https://docs.microsoft.com/en-us/azure/cognitive-services/containers/docker-compose-recipe

The major issue with this is we want to rainbow-bridge to be across cloud providers, just as testnet, this bounds you to provider specific solutions, such as ECS for AWS, while kubernete clusters can cross cloud providers

**Comment by ailisp** [comment]
If time not permitted, I agree with pm2 + docker-compose for local development and ci purpose, but for production, we need either 
1) instances with pm2, use reasonable monitor and restart fail, setup reasonable deploy/rollback toolings such as AWS CodeDeploy or ansible playbooks
2) deploy in kubernetes cluster, a helm chart gives us good robustness and easilly deploy/rollback/update/scale deployment.

So why not spend a little more time write helm chart, even locally it's better than docker-compose. Most developers use mac and mac docker comes with a local k8s cluster

**Comment by chefsale** [comment]
So, if I undertstood correctly from @nearmax that this will be ran not only from us, but from everybody else. I don't agree that docker-compose is only for development as you can ran it on every major cloud provider, as well on kubernetes which in my opinion is a better solution. Not limiting yourself to one specific type of orchestration.

As and said it's not one cloud, it's all of them:

> For more reference here:
> AWS:
> https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html
> 
> Azure:
> https://docs.microsoft.com/en-us/azure/cognitive-services/containers/docker-compose-recipe
> 
> Kubernets based cloud: https://stackoverflow.com/questions/37845715/can-kubernetes-be-used-like-docker-compose
> 
> Same for all the others, but the problem is helm is kubernetes only which is a more specialized tool, so in my opinion we should stick to docker compose.

Aka you can deploy docker-compose on Kubernetes, but not vice versa.

**Comment by ailisp** [comment]
> As and said it's not one cloud, it's all of them:

No you cannot deploy a docker-compose as a single unit in AWS ECS and in Azure CoginiiveServices, You're deploying two units of rainbow bridge, not one unit across cloud

**Comment by ailisp** [comment]
> Aka you can deploy docker-compose on Kubernetes, but not vice versa.

Why do you want deploy docker-compose on k8s? As I said, it's
1) incomplete, you need additional resources like ingress to make it work
2) you cannot atomically use helm to upgrade/rollback all services as a whole unit, without helm chart, which is hard to manage

Also helm chart alone is simpler to use than a docker-compose, even locally

**Comment by chefsale** [comment]
In case if helm is simple to setup, we can just do both and let people choose what they want to use.

**Comment by ailisp** [comment]
> In case if helm is simple to setup, we can just do both and let people choose what they want to use.

Why do both if one is superset of the other. I think their maybe more developers familiar with docker than kubernetes, but a few lines instructions will get people started and get a better experience.

```
mac: install docker, brew install helm
helm install rainbow-bridge-local near/rainbow-bridge
```
For better experience, i'm giving a few common use cases:
1. update one of the docker image version
2. update one env var of one service
3. local development, update source code, build new docker image
In either case, you need docker-compose down and up, with helm they're one liner, and one liner to rollback. In 3, you need docker-compose down, docker-compose build and docker-compose up, with helm/k8s, you can build the image with all services running, and just kill pod of that service, and it'll restart with your new image. Can this three use cases convince you even local k8s is a better developer experience than docker-compose? 

And by the way, we get production level definition of rainbow-bridge that can run in any k8s cluster, this is much more robust than docker-compose on production

**Comment by chefsale** [comment]
That was exactly my point, but the other way around. Docker compose is a superset of helm and can be run anywhere and you don't run it with docker-compose up, but you give the same configuration to the orchestration system whatever that is.

**Comment by ailisp** [comment]
> That was exactly my point, but the other way around. Docker compose is a superset of helm and can be run anywhere and you don't run it with docker-compose up, but you give the same configuration to the orchestration system whatever that is.

I don't think in feature and production-ready devops sense docker-compose is any way superset than k8s. The benefit is easy to use for local development (if docker-compose file inexist, and you need to quickly write a docker-compose file), If people have wrote a helm chart and the docker-compose for the service, then run with helm install is easier to use and more powerful

**Comment by nearmax** [comment]
FYI It is very unlikely that we will encounter scaling issues with the bridge. 
In production bridge will require the following services:
* Eth2NearRelay (currently working);
* Near2EthRelay (currently not fully setup, due to misconfigured ENV variables);
* NearClientValidator (currently not implemented).
These services consume little resources and will not be affected by the usage or popularity of the bridge. Also, there will be no advantage in spinning up more than one instance of each service. Therefore docker compose is sufficient from the perspective of the scalability. Btw, just like @ailisp I was under impression that docker compose is for local development, while docker swam is for production. Docker swarm however is not reliable from my experience -- the documentation has been changed frequently and is not good, there are some ugly hacks that I had to perform to make it work properly. However, time is a major factor here, so I suggest we temporarily use whatever solution is faster to implement -- it is not clear to me from the above discussion whether docker compose or helm will be faster.

> So, if I undertstood correctly from @nearmax that this will be ran not only from us, but from everybody else.

Correct, various large clients would want to run their own relayers and validator.

FYI, for testing purposes we might add several more services:
* Eth2NearProver tester (currently not parallelized);
* Near2EthProver tester (currently not implemented);
* AdversarialNear2EthRelay (currently not implemented).

Additionally for local development we might want to spin up the following services:
* Local Near node;
* Ganache.

In the future we might want to add the following to the setup:
* Dedicated dashboard to monitor bridge activity;
* Functionality for calling contacts across the bridge -- this will be a whole set of services and websites, and is a large project on its own.

Overall, I suggest we converge on a set of technologies for use for the devops in our company to reduce the maintenance. E.g. if we pick kubernetes for one project that we should prefer using it for other projects too.

**Comment by chefsale** [comment]
Yep, agree with everything said, the only thing which I believe there is a misunderstanding. When you create a docker-compose file you can run it either:
1. **docker-compose binary (docker-compose up, stop**, etc) which is created for single machine, as you said mostly use for local development or single machine deployments
2. **by other orchestration systems** (AWS ECS, Azure Cloud, Kubernetes, etc.) because they all know how to **interpret the compose.yaml file** and you use that to spin up docker, you are still able to use all the full capabilities of the "cloud".

So, my only point is for now if we run docker compose up, it's gonna be good enough for one machine deployment, but still in case we need **we can just run these docker containers on top of a cloud provider (read orchestration system) without any changes** because they know how to consumer these configs and create proper orchestrated distributed cloud deployments.

As well, we are using docker everywhere else and it's a standard, if we limit ourselves to kubernetes exclusive technology we have to use it both anywhere and doesn't provide us the same flexibility.

**Comment by nearmax** [comment]
@ailisp Now that we have a test with the headers, could you please fix the CI and make sure it runs on it?

**Comment by ailisp** [comment]
> @ailisp Now that we have a test with the headers, could you please fix the CI and make sure it runs on it?

Sure. how to increase the gas for the test? It run out of gas when processing too many blocks

**Comment by nearmax** [comment]
You can set very high gas limit by manually setting `near_sdk::env::set_blockchain_interface` instead of using `testing_env!` macro. See what this macro unfolds into here: https://github.com/near/near-sdk-rs/blob/5d66300a8ec825c4b62901a7b426cf9508170d5e/near-sdk/src/lib.rs#L28 Instead of passing `Default::default()` for `VMConfig` you need to first create `VMConfig::free()`.

**Comment by ailisp** [comment]
I passed VMConfig::free() now, but run into another issue 😅 
```
thread 'tests::predumped_block_can_be_added' panicked at 'called `Result::unwrap()` on an `Err` value: HostError(NumberOfLogsExceeded { limit: 100 })', /Users/bo/.cargo/registry/src/github.com-1ecc6299db9ec823/near-bindgen-0.4.2/src/environment/mocked_blockchain.rs:157:9
```

**Comment by nearmax** [comment]
After creating `VMConfig` using `free` we can override `vm_config.limit_config.max_number_logs = U64::MAX`.
