### ISSUE TITLE
Trustless Near-Eth Bridge w Token

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#6]
Includes the following:
- [ ] Trustless Eth client in Rust;
- [ ] Eth verifier in Rust;
- [ ] Trustless Near client in Solidity;
- [ ] Near verifier in Solidity;
- [ ] Token example that works in both directions.

**Comment by nearmax** [comment]
Closing this in favor of https://github.com/nearprotocol/nearcore/issues/2063 do de-clutter issues.

**Comment by nearmax** [comment]
Reopening it since we expand the scope to fully trustless bridge.

**Comment by nearmax** [comment]
Removing issues from this Epic since @k06a uses Github project to track the progress.

**Comment by ilblackdragon** [comment]
Why don't we use ZenHub to track the progress here to align with the rest of NEAR Collective work?

**Comment by nearmax** [comment]
@k06a , could you please use Zenhub for tracking?

**Comment by k06a** [comment]
@nearmax sure,  will do
