### ISSUE TITLE
near start near-node starts on the second attempt

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#94]
Execute the following from the `environment` folder:
```bash
node index.js clean
node index.js prepare --bridge-src /Users/maksymzavershynskyi/Projects/rainbow-bridge --core-src /Users/maksymzavershynskyi/Projects/nearcore --nearup-src /Users/maksymzavershynskyi/Projects/nearup 
```
(Update the paths to your local folder)
```bash
node index.js start near-node
```
Observe the output:
```
Nearup is installed to ~/.nearup!
```
Go to http://localhost:3030/status to ensure that the node did not start.
Then run it again:
```bash
node index.js start near-node
```
Observe the output:
```
Jun 16 17:02:36.034  INFO near: Version: 1.1.0, Build: c100e57c, Latest Protocol: 25    
Jun 16 17:02:36.041  INFO near: Generated node key, validator key, genesis file in /Users/maksymzavershynskyi/.near/localnet/node0    
Local network was spawned successfully.
Check logs at: /Users/maksymzavershynskyi/.nearup/localnet-logs
Check network status at http://127.0.0.1:3030/status
```
This time the node has started. This behavior is consistent.

# Expected
The node to start on the first command.

**Comment by nearmax** [comment]
FYI ganache also sometimes takes two tries to start, it is however inconsistent, sometimes it starts with one. The node, in contrast, always takes two tries to start.

**Comment by chefsale** [comment]
So, this maybe is a bug in nearup, not sure. @ailisp have you maybe some context on why would nearup on the first run just output:
```
Nearup is installed to ~/.nearup!
```
and than on the second run actually run it?

**Comment by chefsale** [comment]
> FYI ganache also sometimes takes two tries to start, it is however inconsistent, sometimes it starts with one. The node, in contrast, always takes two tries to start.

On this one, I will try to dig into this one today.

**Comment by chefsale** [comment]
**I have confirmed that this looks like a bug in nearup:**
```
sandi@sandi-ThinkPad-X1-Carbon-7th ~/w/n/b/environment (dockerization)> ~/.rainbowup/nearup/nearup localnet --num-nodes 1 --binary-path ~/.rainbowup/core/target/debug
Local network was spawned successfully.
Check logs at: /home/sandi/.nearup/localnet-logs
Check network status at http://127.0.0.1:3030/status

sandi@sandi-ThinkPad-X1-Carbon-7th ~/w/n/b/environment (dockerization)> ~/.rainbowup/nearup/nearup stop
Stopping process /home/sandi/.rainbowup/core/target/debug/neard --home /home/sandi/.near/localnet/node0 run with pid 84353

sandi@sandi-ThinkPad-X1-Carbon-7th ~/w/n/b/environment (dockerization)> rm -rf ~/.nearup/

sandi@sandi-ThinkPad-X1-Carbon-7th ~/w/n/b/environment (dockerization)> ~/.rainbowup/nearup/nearup stop
Nearup is installed to ~/.nearup!

sandi@sandi-ThinkPad-X1-Carbon-7th ~/w/n/b/environment (dockerization)> rm -rf ~/.nearup/

sandi@sandi-ThinkPad-X1-Carbon-7th ~/w/n/b/environment (dockerization)> ~/.rainbowup/nearup/nearup localnet --num-nodes 1 --binary-path ~/.rainbowup/core/target/debug
Nearup is installed to ~/.nearup!
```

So, in case where nearup doesn't have the folder ~/.nearup created it just setups everything:
```
sandi@sandi-ThinkPad-X1-Carbon-7th ~/w/n/b/environment (dockerization)> ls ~/.nearup/
env  main.py  Makefile  nearup*  nearuplib/  README.md  setup.py  watcher.py
```
but it doesn't start the process.

@ailisp @nearmax I believe maybe we should change that it checks if the folder exists and creates the folder if not or maybe move it to the same model as rainbowup, with a prepare command.

_**On the ganache side I'm still investigating.**_

**Comment by chefsale** [comment]
Created a fix, reversed the logic: https://github.com/near/nearup/pull/77.

cc: @nearmax @ailisp
